// SPDX-License-Identifier: Apache-2.0
// The Action red-team PoCs of 2026-10-06 (rt-poc/ws, generated by rt-poc/gen.mjs; copied verbatim into
// test/vectors/rt-poc/) replayed against the v2 bundle. Every one must be REJECTED, offline.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, symlinkSync, copyFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { ROOT, workspace, runAction, injectedCommandLines } from './support/runner.mjs';

const POC = path.join(ROOT, 'test', 'vectors', 'rt-poc');
const GENUINE_FILE = path.join(ROOT, 'test', 'vectors', 'genuine-fe62b072.json');
const GOV_ATTACKER = readFileSync(path.join(POC, 'gov-key.txt'), 'utf8').trim();
const REAL_GOV = JSON.parse(readFileSync(path.join(ROOT, 'test', 'vectors', 'key-directory-epoch3.json'), 'utf8')).directory_public_key;
function ws() {
  const w = workspace();
  for (const f of ['attacker-dir.json', 'backdated-served.json', 'dup-dir.json', 'evil-dir.json', 'forged.json', 'gov-dir-retiring.json', 'inject.json', 'trusted-keys.txt']) copyFileSync(path.join(POC, f), path.join(w, f));
  copyFileSync(GENUINE_FILE, path.join(w, 'g.json'));
  copyFileSync(GENUINE_FILE, path.join(w, 'a'.repeat(64))); // P5
  symlinkSync('/etc/hosts', path.join(w, 'link-receipt.json')); // P4
  copyFileSync(path.join(ROOT, 'test', 'vectors', 'key-directory-epoch3.json'), path.join(w, 'real-dir.json'));
  return w;
}
const codes = (r) => (r.out.codes || '').split(',');
const rejected = (r, msg) => { assert.equal(r.out.valid, 'false', `${msg}\n${r.log}`); assert.equal(r.code, 1, msg); assert.deepEqual(injectedCommandLines(r.log), [], msg); };

test('P1/P2 inject.json: workflow-command / markdown payload is rejected and neutralised', async () => {
  const r = await runAction(ws(), { receipt: 'inject.json', 'key-directory': 'real-dir.json' });
  rejected(r, 'inject'); assert.ok(!r.sum.includes('<img'));
});
test('P3 evil-dir.json: directory with a shell payload in epoch is refused and the epoch never surfaces', async () => {
  const r = await runAction(ws(), { receipt: 'g.json', 'key-directory': 'evil-dir.json' });
  rejected(r, 'evil-dir'); assert.equal(r.out.epoch, ''); assert.ok(codes(r).includes('DIRECTORY_INVALID'), r.out.codes);
});
test('P4 link-receipt.json -> /etc/hosts: refused, not echoed', async () => {
  const r = await runAction(ws(), { receipt: 'link-receipt.json', 'key-directory': 'real-dir.json' });
  rejected(r, 'symlink'); assert.ok(!/Host Database|localhost/i.test(r.log + r.sum));
});
test('P5 file named like a receipt id: fetched by id (bound), never read from the workspace', async () => {
  const r = await runAction(ws(), { receipt: 'a'.repeat(64), 'key-directory': 'http://127.0.0.1:9/.well-known/x402-receipt-keys' }, { extraEnv: { PQC_VERIFY_FETCH_TIMEOUT_MS: '1000' } });
  rejected(r, 'id shadow'); assert.match(r.out.reason, /127\.0\.0\.1:9\/api\/midas\/alerts\/receipt\/a{64}/);
});
test('P7 trusted-keys.txt with only comments: refused (NO_TRUST_SOURCE), no silent fallback to the directory', async () => {
  const r = await runAction(ws(), { receipt: 'g.json', 'trusted-keys': 'trusted-keys.txt', 'key-directory': 'real-dir.json' });
  rejected(r, 'empty pin'); assert.ok(codes(r).includes('NO_TRUST_SOURCE'));
});
test('P8 forged.json + attacker-dir.json: attacker-governed directory refused by the pinned root', async () => {
  const w = ws();
  const r = await runAction(w, { receipt: 'forged.json', 'key-directory': 'attacker-dir.json' });
  rejected(r, 'forged'); assert.ok(codes(r).includes('DIRECTORY_SIGNER_NOT_PINNED'), r.out.codes); assert.equal(r.out.authentic, 'true');
  rejected(await runAction(w, { receipt: 'forged.json', 'key-directory': 'attacker-dir.json', 'governance-key': REAL_GOV }), 'forged+real gov');
  rejected(await runAction(w, { receipt: 'forged.json', 'key-directory': 'real-dir.json' }), 'forged+real dir');
});
test('P9 backdated-served.json: retiring key + unsigned backdated emitted_at refused, even with the attacker governance pinned', async () => {
  const w = ws();
  for (const inputs of [
    { receipt: 'backdated-served.json', kind: 'served-proof', 'key-directory': 'gov-dir-retiring.json' },
    { receipt: 'backdated-served.json', kind: 'served-proof', 'key-directory': 'gov-dir-retiring.json', 'governance-key': GOV_ATTACKER },
    { receipt: 'backdated-served.json', 'key-directory': 'gov-dir-retiring.json', 'governance-key': GOV_ATTACKER },
  ]) rejected(await runAction(w, inputs), JSON.stringify(inputs));
  const r = await runAction(w, { receipt: 'backdated-served.json', kind: 'served-proof', 'key-directory': 'gov-dir-retiring.json', 'governance-key': GOV_ATTACKER });
  assert.ok(codes(r).includes('KEY_NEEDS_SIGNED_TIME'), r.out.codes);
});
test('P10 dup-dir.json: a key listed twice (active + revoked) is refused', async () => {
  const w = ws();
  rejected(await runAction(w, { receipt: 'forged.json', 'key-directory': 'dup-dir.json' }), 'dup');
  const r = await runAction(w, { receipt: 'forged.json', 'key-directory': 'dup-dir.json', 'governance-key': GOV_ATTACKER });
  rejected(r, 'dup+gov'); assert.ok(codes(r).includes('DIRECTORY_INVALID'), r.out.codes);
});
test('control: the genuine receipt in the same workspace verifies (pinned-root)', async () => {
  const r = await runAction(ws(), { receipt: 'g.json', 'key-directory': 'real-dir.json' });
  assert.equal(r.out.valid, 'true', r.log); assert.equal(r.out['trust-basis'], 'pinned-root');
  assert.ok(existsSync(POC));
});
